package com.example.jarvis

import org.json.JSONException
import org.json.JSONObject
import android.util.Log

/**
 * Sandboxed Tool Manager responsible for parsing JSON output from the LLM
 * and validating it against a strict set of allowed actions.
 */
class ToolManager {

    companion object {
        private const val TAG = "ToolManager"
    }

    /**
     * Defines the strict set of allowed actions the Agent can perform.
     * This acts as the Sandbox to prevent arbitrary command execution.
     */
    enum class SecureAction {
        MAKE_CALL,
        SEND_MESSAGE,
        CREATE_NOTE,
        UNKNOWN // Fallback for invalid or hallucinated actions
    }

    /**
     * Represents a parsed and validated command from the LLM.
     */
    data class AgentCommand(
        val action: SecureAction,
        val target: String? = null,
        val payload: String? = null
    )

    /**
     * Parses the JSON output from the LLM.
     * Expects format: {"action": "MAKE_CALL", "target": "1234567890"}
     *
     * @param jsonString The raw JSON string generated by the LLM.
     * @return AgentCommand The validated command, or an UNKNOWN action if invalid.
     */
    fun parseCommand(jsonString: String): AgentCommand {
        try {
            // Remove markdown code blocks if the LLM adds them
            val cleanJson = jsonString.trim()
                .removePrefix("```json")
                .removePrefix("```")
                .removeSuffix("```")
                .trim()

            val jsonObject = JSONObject(cleanJson)
            val actionString = jsonObject.optString("action", "")
            val target = jsonObject.optString("target", null)
            val payload = jsonObject.optString("payload", null)

            // Strict Sandboxing: Map the string to our SecureAction Enum
            val secureAction = when (actionString.uppercase()) {
                "MAKE_CALL" -> SecureAction.MAKE_CALL
                "SEND_MESSAGE" -> SecureAction.SEND_MESSAGE
                "CREATE_NOTE" -> SecureAction.CREATE_NOTE
                else -> {
                    Log.w(TAG, "Unrecognized action attempted: $actionString")
                    SecureAction.UNKNOWN
                }
            }

            return AgentCommand(action = secureAction, target = target, payload = payload)

        } catch (e: JSONException) {
            Log.e(TAG, "Failed to parse LLM JSON: $jsonString", e)
            // Handle hallucination / bad JSON by returning UNKNOWN
            return AgentCommand(action = SecureAction.UNKNOWN)
        }
    }
}
